### ISSUE TITLE
Genotype strategy

### ISSUE THREAD

**Issue by coh-racng** [huangyh09/vireo#1]
What is the recommended way to obtain genotype information for assigning donor id that is also cost effective? 
How does using genotype array compare with using variants called on bulk rna seq or bulk exome seq?

**Comment by huangyh09** [comment]
Hi, as you may already notice that vireo outputs the estimated genotype for each donor, which you can use to identify the sample id. 
I'm not familiar with the cost of these sequencing platforms, but all of the three (genotype array, bulk RNA-seq and bulk exome-seq) work very well in my experience. I believe other 'omics data, e.g., ATAC-seq, CHiP-seq, will do it well too.
